[package]
name = "hydradx-traits"
version = "2.0.0"
description = "Shared traits"
authors = ["GalacticCouncil"]
edition = "2021"
license = "Apache 2.0"
repository = "https://github.com/galacticcouncil/warehouse/tree/master/traits"

[dependencies]
codec = { default-features = false, features = ["derive"], package = "parity-scale-codec", version = "3.1.5" }
scale-info = { version = "2.1.2", default-features = false, features = ["derive"] }
serde = { features = ["derive"], optional = true, version = "1.0.137" }
impl-trait-for-tuples = "0.2.2"
sp-arithmetic = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37", default-features = false }

# Substrate dependencies
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37", default-features = false }

[features]
default = ["std"]
std = [
    "serde",
    "codec/std",
    "frame-support/std",
    "sp-std/std",
]
